### ISSUE TITLE
URL Unreachable: dcos cluster setup

### ISSUE THREAD

**Issue by Bowiemb** [dcos-labs/terraform-ansible-dcos#21]
When I run `dcos cluster setup http://xxx.xx.xx.xx`

I get the following error: `URL [http://xxx.xx.xx.xx/acs/api/v1/auth/login] is unreachable.`

I'm running this on an open stack cluster. 

Any pointers in the right direction?

Thanks!

**Comment by jrx** [comment]
Hi,

seems like you have a general connectivity issue reaching your machines on port 443 and 80. Did you install them via Ansible? If yes, please ping me in the chat http://chat.dcos.io/ my user name is `jrx.mesosphere`. I think it's better suited for trouble shooting your issue instead of github.

In general, you can also take a look at:
https://docs.mesosphere.com/1.11/installing/oss/troubleshooting/

Best,
Jan
